### ISSUE TITLE
How to use variables with handlebars

### ISSUE THREAD

**Issue by ApfelUser** [i18next/i18next-node#199]
According to the documentation at the [templates](http://i18next.com/node/pages/doc_templates.html) section it is possible to use variables in Jade like **this:**

```jade
p=t("my.translation.key", { my: "variable" })
```
how can I make this work with [handlebars](https://www.npmjs.com/package/hbs)?

This:

```hbs
<p>{{t 'my.translation.key', [ my: "variable" ] }}</p>
```

This:

```hbs
<p>{{t 'my.translation.key', { my: "variable" } }}</p>
```

And this:

```hbs
<p>{{t 'my.translation.key', ( my: "variable" ) }}</p>
```

all crash with:

```
Error: /Users/github/Documents/i18n_hbs/views/home.hbs: Parse error on line 115:
...al.nav.link.testing', ( my : "variable" ) 
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'DATA', got 'INVALID'
    at Object.parseError (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:150:11)
    at Object.parse (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:202:22)
    at HandlebarsEnvironment.parse (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:25:30)
    at compileInput (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:451:19)
    at ret (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:460:18)
    at Object.invokePartial (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:12)
    at Object.invokePartialWrapper [as invokePartial] (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:47:39)
    at Object.eval (eval at <anonymous> (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:209:23), <anonymous>:5:26)
    at ret (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:144:30)
    at ret (/Users/github/Documents/i18n_hbs/node_modules/hbs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:462:21)
    at /Users/github/Documents/i18n_hbs/node_modules/hbs/lib/hbs.js:62:19
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Is there some helper I need to add? And if yes, which one?

Cheers,

Silas

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_templates.html is for clientside but might be same for serverside...

just be sure to use the t function on request object to assert you get translations in users language.

**Comment by ApfelUser** [comment]
Sorry, put the wrong documentation link in there. [Here](http://i18next.com/node/pages/doc_features.html#interpolation) is the right one. I think you understood me wrong, sorry for that. Translation is already working, but variables aren't. (Like names, links etc.)

**Comment by jamuhl** [comment]
not sure but according to http://handlebarsjs.com/expressions.html#helpers you need to use triple {

`<p>{{{t 'my.translation.key', ( my: "variable" ) }}}</p>`

but not sure as i never used handlebars on serverside.

**Comment by ApfelUser** [comment]
@jamuhl Nope, that doesn't work. Thanks for trying to help though! I am adding the maintainers of [hbs](https://github.com/donpark/hbs) and [handlebars](https://github.com/wycats/handlebars.js) to this so they can maybe help.

/cc @kpdecker & @defunctzombie

**Comment by kpdecker** [comment]
That syntax is invalid. You want something like `{{t 'foo' my='variable'}}` That will populate `options.hash` with `{my: 'variable'}`. That means your `t` implementation needs to expect this and not a generic hash structure.

**Comment by ApfelUser** [comment]
@kpdecker 

I tried it with

```javascript
handlebars.registerHelper('t', function(key, options) {
  // The console.log's are added by me
  console.log(key)
  console.log(options)
  var result = i18n.t(key, options);
  console.log(result)
  return new handlebars.SafeString(result);
});
```

from the **[Template Documentation](http://i18next.com/pages/doc_templates.html)**

The **console log** shows:

**key:**

```
my.translation.key
````

**options:**

```
{ name: 't',
  hash: { my: 'variable' },
  data:
   { root:
      { settings: [Object],
        some: 'othervars',
        _locals: {},
        cache: false } } }
```

**result:**

```
test __my__ test
```

So something isn't working, but I think that the problem is more on my or i18next's side.

Any ideas @jamuhl?

Cheers,

Silas

**Comment by kpdecker** [comment]
I suspect that you want something like:

```
  var result = i18n.t(key, options.hash);

```

**Comment by ApfelUser** [comment]
@kpdecker Thanks so much! That worked. I am writing it down here for people with the same issue:

```javascript
handlebars.registerHelper('t', function(key, options) {
  var result = i18n.t(key, options.hash);
  return new handlebars.SafeString(result);
});
```
@jamuhl Do you maybe want to add this to the documentation? I could too, but didn't find a repository for it.

/closing

**Comment by jamuhl** [comment]
yes will add this to doc. thanks to all for solving this.

**Comment by jamuhl** [comment]
closing...handlebars will not be in docs anylonger. hope someone will come up with some plugin for handlebars for v2 of i18next: http://i18next.github.io/i18next.com/docs/ecosystem/#frameworks
