### ISSUE TITLE
Cannot read property '_translationTable' of undefined - i18next on OSX and docker

### ISSUE THREAD

**Issue by nkhine** [i18next/i18next-node#204]
hello, i have a website that uses i18next to for localization. all works fine, on ubuntu and freebsd, but when i try to run this on OSX or in a docker instance, i get the following traceback

```
    /Users/khinester/Sandboxes/node-blade-boiler-template/node_modules/i18next.gettext/node_modules/i18next-conv/lib/gettextWrapper.js:218
    				callback(null, gt._domains[domain]._translationTable);
    				                                  ^
    TypeError: Cannot read property '_translationTable' of undefined
      at /Users/khinester/Sandboxes/node-blade-boiler-template/node_modules/i18next.gettext/node_modules/i18next-conv/lib/gettextWrapper.js:218:39
      at fs.js:272:14
      at Object.oncomplete (fs.js:108:15)
```

and on the docker logs

```
     Aug 26 14:23:50 80c8aebbf8ea web-dev:     --> reading file from: locales/es-ES.po 
    Aug 26 14:23:50 80c8aebbf8ea web-dev:     --> reading file from: locales/es.po 
    Aug 26 14:23:50 80c8aebbf8ea web-dev:               callback(null, gt._domains[domain]._translationTable); 
    Aug 26 14:23:50 80c8aebbf8ea web-dev: /usr/src/app/node_modules/i18next.gettext/node_modules/i18next-conv/lib/gettextWrapper.js:218 
    Aug 26 14:23:50 80c8aebbf8ea web-dev:                                                 ^ 
    Aug 26 14:23:50 80c8aebbf8ea web-dev: TypeError: Cannot read property '_translationTable' of undefined 
    Aug 26 14:23:50 80c8aebbf8ea web-dev:   at fs.js:272:14 
    Aug 26 14:23:50 80c8aebbf8ea web-dev:   at /usr/src/app/node_modules/i18next.gettext/node_modules/i18next-conv/lib/gettextWrapper.js:218:39 
    Aug 26 14:23:50 80c8aebbf8ea web-dev:   at Object.oncomplete (fs.js:108:15) 
```

any advice much appreciated

**Comment by jamuhl** [comment]
hard to say...even more as even harder to reproduce your env. sorry for that. Any PR fixing this would be very welcome.

**Comment by jamuhl** [comment]
upcoming v2: http://i18next.github.io/i18next.com/

i18next-node will be replaced by https://github.com/i18next/i18next-express-middleware

PRs welcome
