### ISSUE TITLE
t is not a function

### ISSUE THREAD

**Issue by stefanotto** [i18next/i18next-node#215]
Node/i18next crashes sporadically (but regularly) when serving 404 pages through a default route.
The route is mounted behind my localized SEO routes in i18n.init's callback.

```
TypeError: /srv/www/mainsite-live/sites/not-found.jade:4
2| html(lang='en')
3|   include mixins/head
> 4|   +head(t('not-found:title'), 'not-found')
5|   body
6|     include ./partials/navigation
7|     .container
t is not a function
at eval (eval at <anonymous> (/srv/www/mainsite-live/node_modules/jade/lib/index.js:218:8), <anonymous>:62:21)
at eval (eval at <anonymous> (/srv/www/mainsite-live/node_modules/jade/lib/index.js:218:8), <anonymous>:499:22)
at res (/srv/www/mainsite-live/node_modules/jade/lib/index.js:219:38)
at Object.exports.renderFile (/srv/www/mainsite-live/node_modules/jade/lib/index.js:380:38)
at Object.exports.renderFile (/srv/www/mainsite-live/node_modules/jade/lib/index.js:370:21)
at View.exports.__express [as engine] (/srv/www/mainsite-live/node_modules/jade/lib/index.js:417:11)
at View.render (/srv/www/mainsite-live/node_modules/express/lib/view.js:126:8)
at tryRender (/srv/www/mainsite-live/node_modules/express/lib/application.js:639:10)
at EventEmitter.render (/srv/www/mainsite-live/node_modules/express/lib/application.js:591:3)
at ServerResponse.render (/srv/www/mainsite-live/node_modules/express/lib/response.js:961:7)
at /srv/www/mainsite-live/routes.js:64:11
at Layer.handle [as handle_request] (/srv/www/mainsite-live/node_modules/express/lib/router/layer.js:95:5)
at next (/srv/www/mainsite-live/node_modules/express/lib/router/route.js:131:13)
at Route.dispatch (/srv/www/mainsite-live/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/srv/www/mainsite-live/node_modules/express/lib/router/layer.js:95:5)
at /srv/www/mainsite-live/node_modules/express/lib/router/index.js:277:22
```

Any idea? I know the module is deprecated and I will migrate to version 2 soon, but I need this to work before that. The problem only became apparent when the site went live with a decent amount of requests.

**Comment by jamuhl** [comment]
if this issue comes unregular - sounds for me like a memory leak in express...or at least i not see how this could be related to i18next-node - only adds the t function to req.locals in the handle function....

sorry no idea....

**Comment by stefanotto** [comment]
Ok, thanks. That was helpful anyway.

**Comment by jamuhl** [comment]
you found the cause?

**Comment by jamuhl** [comment]
more info?

**Comment by stefanotto** [comment]
Just looked into it again and I can now reproduce the problem.

As I've said it always occurs inside the middleware handling 404 responses:

```
app.use(function(req, res, next) {
      res.render('not-found', req.templateData);
});
```

This works for any non-existing route, but always produces the error when dealing with static content, `<host>/css/<some-non-existent-file>` for example.

I don't get that. At that point i18next has already been initialized.

**Comment by jamuhl** [comment]
did you append that before the i18next.handle?

**Comment by stefanotto** [comment]
No.

```
// ...
i18n.registerAppHelper(app);
app.use(i18n.handle);

require(__basedir + '/routes')(app, i18n);
//...
```

To be sure, I added the middleware at the end of i18n.init's callback.

**Comment by jamuhl** [comment]
so it's not the order...

```
app.use(i18n.handle) // --> adds t
app.use(function(req, res, next) { // --> t undefined here
      res.render('not-found', req.templateData);
});
```

really got no idea...best you run through debugger...or add some logs to the i18next.handle fc
